### ISSUE TITLE
rdfs.n3s test failes on Cannot read properties of null

### ISSUE THREAD

**Issue by phochste** [joachimvh/tension.js#1]
[[https://github.com/eyereasoner/rdfsurfaces-tests/blob/main/test/pure/rdfs.n3s](https://github.com/eyereasoner/rdfsurfaces-tests/blob/main/test/pure/rdfs.n3s) test failes with:

```
/Users/hochsten/github.com/joachimvh/tension.js/node_modules/n3/lib/N3Store.js:40
    if (id[0] === '.') {
          ^

TypeError: Cannot read properties of null (reading '0')
    at N3Store._termFromId (/Users/hochsten/github.com/joachimvh/tension.js/node_modules/n3/lib/N3Store.js:40:11)
    at N3Store._findInIndex (/Users/hochsten/github.com/joachimvh/tension.js/node_modules/n3/lib/N3Store.js:139:35)
    at _findInIndex.next (<anonymous>)
    at N3Store.readQuads (/Users/hochsten/github.com/joachimvh/tension.js/node_modules/n3/lib/N3Store.js:395:23)
    at readQuads.next (<anonymous>)
    at N3Store.getQuads (/Users/hochsten/github.com/joachimvh/tension.js/node_modules/n3/lib/N3Store.js:366:21)
    at removeDuplicateBlankNodes (/Users/hochsten/github.com/joachimvh/tension.js/dist/ClauseUtil.js:18:32)
    at run (/Users/hochsten/github.com/joachimvh/tension.js/dist/Run.js:45:97)
    at Object.<anonymous> (/Users/hochsten/github.com/joachimvh/tension.js/bin/tension.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)

Node.js v20.9.0
```

**Comment by joachimvh** [comment]
Fixed in https://github.com/joachimvh/tension.js/commit/15f431683666479458fd9c7cad86d9ac4845ccd8
