### ISSUE TITLE
negativeSurface:FAIL.n3s failes with Unexpected formula: {"@graph":{"@list":[],"log:onNegativeSurface":{"@graph":[]}}}

### ISSUE THREAD

**Issue by phochste** [joachimvh/tension.js#2]
https://github.com/eyereasoner/rdfsurfaces-tests/blob/main/test/pure/negativeSurface%3AFAIL.n3s fails with:

```
/Users/hochsten/github.com/joachimvh/tension.js/dist/ParseUtil.js:31
        throw new Error(`Unexpected formula: ${JSON.stringify(graph)}`);
              ^

Error: Unexpected formula: {"@graph":{"@list":[],"log:onNegativeSurface":{"@graph":[]}}}
    at parseFormula (/Users/hochsten/github.com/joachimvh/tension.js/dist/ParseUtil.js:31:15)
    at parseRoot (/Users/hochsten/github.com/joachimvh/tension.js/dist/ParseUtil.js:27:12)
    at run (/Users/hochsten/github.com/joachimvh/tension.js/dist/Run.js:44:46)
    at Object.<anonymous> (/Users/hochsten/github.com/joachimvh/tension.js/bin/tension.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.9.0
```

**Comment by joachimvh** [comment]
Fixed in https://github.com/joachimvh/tension.js/commit/72a920f5c4c312e1d4859c91340491bae27e68ad
